### ISSUE TITLE
Integrate with opendal

### ISSUE THREAD

**Issue by Xuanwo** [spring-rs/spring-rs#13]
Hi, thanks for creating Spring Rust! I'm from the [OpenDAL](https://github.com/apache/opendal) community and I'm considering whether we could collaborate to build a Spring integration for OpenDAL.

https://github.com/apache/opendal

> OpenDAL offers a unified data access layer, empowering users to seamlessly and efficiently retrieve data from diverse storage services. Our goal is to deliver a comprehensive solution for any languages, methods, integrations, and services.

![image](https://github.com/user-attachments/assets/e8912549-82c0-43a0-8ab7-1aef86b6ac75)

By adding opendal integration, users can visit s3, azbobl, oss, obs and more storage services.

What do you think?

**Comment by holmofy** [comment]
OpenDAL looks like a good project. But this project is my side job, so this task has a lower priority. I need to finish the previous tasks before I can start this. If you are interested in implementing it, welcome to submit a pull request. The spring-rs extension plugin is very convenient.
