### ISSUE TITLE
Integrate with nacos

### ISSUE THREAD

**Issue by GreenAppleOne** [spring-rs/spring-rs#15]
希望能集成 nacos，配置中心 服务中心

**Comment by holmofy** [comment]
这个会在集成[rpc框架的时候](https://github.com/spring-rs/spring-rs/issues/14)一起搞

**Comment by holmofy** [comment]
不过nacos这玩意儿太重了，我在考虑有没有替代品

**Comment by Liangdi** [comment]
k8s 算太重吧， r-nacos 作为可选挺好的，我现在用 podman 部署，用 nacos 做配置管理和服务器发现中间件，是不错的选择

**Comment by holmofy** [comment]
@Liangdi podman没怎么用过。你是用docker compose类似的单机容器编排的工具吗？

**Comment by Liangdi** [comment]
> @Liangdi podman没怎么用过。你是用docker compose类似的单机容器编排的工具吗？

对， podman 是默认 rootless 的容器管理工具，没有守护进程，方便控制，也支持 compose 和 docker 基本兼容吧

**Comment by holmofy** [comment]
在一台机器上要啥服务发现，直接用compose指定的service name不好吗

**Comment by Liangdi** [comment]
> 在一台机器上要啥服务发现，直接用compose指定的service name不好吗

^-^ 主要是大多数时候主应用很难做到 stateless , 所以希望某些模块功能更新的时候不影响主业务，就采用微服务的方式集成了

**Comment by GreenAppleOne** [comment]
阿里云的 nacos 有 rust 版的 sdk，集成这个就 OK 了吧

**Comment by holmofy** [comment]
@GreenAppleOne 个人精力有限，我这边还在忙另外几个issue，如果要搞得话，这个优先级会比较低。如果有兴趣的话，欢迎提交pull request，遇到什么问题，也欢迎在这里留言。

**Comment by holmofy** [comment]
This is a good suggestion. Friends in the community are welcome to submit a pull request to implement this plugin.

**Comment by holmofy** [comment]
#14 Microservice application design
