### ISSUE TITLE
web middleware

### ISSUE THREAD

**Issue by huangjie0515** [spring-rs/spring-rs#18]
Can you add web middleware use cases to the case, such as token interception verification

**Comment by holmofy** [comment]
there is [login demo](https://github.com/spring-rs/spring-rs/blob/2a3edd77976fe89e9461f6bb9e37e253e73f0de5/examples/web-example/src/main.rs) using JWT.

Please refer to [axum middleware document](https://docs.rs/axum/latest/axum/middleware/index.html) for custom middleware.

If you use custom middleware, you cannot use `auto_config (WebConfigurator)` and need to register routes manually:

```rust
#[tokio::main]
async fn main() {
    App::new()
        .add_plugin(SqlxPlugin)
        .add_plugin(WebPlugin)
        .add_router(router())
        .run()
        .await
}

fn router() -> Router {
    Router::new()
      .typed_route(hello_world)
      .layer(
          ServiceBuilder::new()
              .layer(layer_one)
              .layer(layer_two)
              .layer(layer_three),
      );
}

#[get("/")]
async fn hello_world() -> impl IntoResponse {
    "hello world"
}
```

**Comment by huangjie0515** [comment]
Hi, do you mean that custom middleware and #[auto_config(WebConfigurator)] scan annotation can't exist at the same time?

**Comment by holmofy** [comment]
You can use `spring_web::handler::auto_router()`, which automatically collects all the routes marked by the process macro

**Comment by huangjie0515** [comment]
thank you. Can you build a wechat group or qq group?

**Comment by holmofy** [comment]
I don’t have this plan for now. I can’t stand the bombardment of WeChat. Email is better.

**Comment by huangjie0515** [comment]
I finally solved this problem by upgrading to version 0.0.7, then checking the documentation you provided, and then using chatgpt to finally achieve this feature. Thank you for your help!

**Comment by huangjie0515** [comment]
Is there any recommended documentation for global exception handling? Similar to global exception handling in spring boot

**Comment by holmofy** [comment]
https://github.com/tokio-rs/axum/blob/main/examples/error-handling/src/main.rs

**Comment by huangjie0515** [comment]
I like auto_config (WebConfigurator) in spring-rs, which automatically scans macros to realize path resolution, but other web projects don't seem to use this macro. Is there any disadvantage of this auto_config (WebConfigurator)?

**Comment by holmofy** [comment]
It inserts an initialization constructor at compile time, which you can think of as a static initialization code block in Java. For details, you can refer to https://github.com/dtolnay/inventory and https://github.com/mmastrac/rust-ctor. It is used in vector and https://github.com/dtolnay/typetag
