### ISSUE TITLE
Is there any simple project that use spring-rs?

### ISSUE THREAD

**Issue by steveGuRen** [spring-rs/spring-rs#40]
I am good at java but I am newer in rust, so I want to learn it by running some simple project and then try to do more in rust.

**Comment by holmofy** [comment]
https://github.com/AutoWDS/autowds-backend

**Comment by steveGuRen** [comment]
HaHa~~~,I can't run it well.I think I should write more simple code.

> https://github.com/AutoWDS/autowds-backend
> […](#)
> 在 2024年9月13日，下午6:09，steveGuRen ***@***.***> 写道： ﻿ I am good at java but I am newer in rust, so I want to learn it by running some simple project and then try to do more in rust. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.
