### ISSUE TITLE
How to use database connection pool or redis connection pool in custom middleware

### ISSUE THREAD

**Issue by stackcn** [spring-rs/spring-rs#43]
I want to get the DbConn of sea_orm in the custom middleware, how to deal with it

**Comment by holmofy** [comment]
https://docs.rs/axum/latest/axum/middleware/index.html#accessing-state-in-middleware

As long as you can access state from the middleware, you can get the registered component through `state.app.getComponent::<C>()`.

In spring-web, [AppState](https://github.com/spring-rs/spring-rs/blob/92a4e8d4a53ad3e9dfcd426f7c424eb518cb0fe5/spring-web/src/lib.rs#L83) is a reference to an App.

**Comment by stackcn** [comment]
If you want to get [AppState,](https://github.com/spring-rs/spring-rs/blob/92a4e8d4a53ad3e9dfcd426f7c424eb518cb0fe5/spring-web/src/lib.rs#L83) it seems that you can only get it by implementing a plug-in？ I am still learning and don’t understand it very well.
