### ISSUE TITLE
我用spring-job实现了一个定时器，但定时器并没有执行，

### ISSUE THREAD

**Issue by huangjie0515** [spring-rs/spring-rs#47]
[dependencies]
spring = "0.1.2"
spring-web = "0.1.3"
spring-sqlx = { version= "0.1.1", features = ["mysql"] }
spring-redis = "0.1.1"
spring-job = "0.1.1"
tokio = "1"

以下是代码片段
#[tokio::main]
async fn main() {
    App::new()
        .add_plugin(SqlxPlugin) // 添加插件
        .add_plugin(WebPlugin)
        .add_plugin(RedisPlugin)
        .add_router(router())
        .add_jobs(jobs::all_jobs::jobs())
        .run()
        .await
}

use spring_job::handler::TypedJob;
use spring_job::Jobs;
use crate::jobs::spider_job;

pub fn jobs() ->Jobs{
    Jobs::new().typed_job(spider_job::cron_job)
}

use std::time::SystemTime;
use spring_job::cron;

#[cron("1/10 * * * * *")]
pub async fn cron_job(){
    println!("cron scheduled: {:?}",SystemTime::now());
}

**Comment by huangjie0515** [comment]
The job plug-in is also not registered at startup

**Comment by holmofy** [comment]
```diff
#[tokio::main]
async fn main() {
   App::new()
    .add_plugin(SqlxPlugin) // 添加插件
+   .add_plugin(JobPlugin)
    .add_plugin(WebPlugin)
    .add_plugin(RedisPlugin)
    .add_router(router())
    .add_jobs(jobs::all_jobs::jobs())
    .run()
    .await
}
```

**Comment by huangjie0515** [comment]
好  这个问题解决了！谢谢你的帮助!
