### ISSUE TITLE
My friend and I can't run hello-world examples

### ISSUE THREAD

**Issue by steveGuRen** [spring-rs/spring-rs#48]
*  Executing task: cargo run --package hello-world-example --bin hello-world-example --all-features 

    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/hello-world-example`
2024-09-21T02:25:39.206346Z  INFO spring::app: spring_web::WebPlugin plugin registered    
thread 'main' panicked at spring-sqlx/src/lib.rs:25:14:
sqlx plugin config load failed: DeserializeErr("sqlx", Error { inner: Error { inner: TomlError { message: "missing field `uri`", raw: None, keys: [], span: None } } })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::expect
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1059:23
   4: <spring_sqlx::SqlxPlugin as spring::plugin::Plugin>::build::{{closure}}
             at ./spring-sqlx/src/lib.rs:23:22
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/future/future.rs:123:9
   6: spring::app::AppBuilder::build_plugins::{{closure}}
             at ./spring/src/app.rs:176:40
   7: spring::app::AppBuilder::inner_run::{{closure}}
             at ./spring/src/app.rs:153:30
   8: spring::app::AppBuilder::run::{{closure}}
             at ./spring/src/app.rs:137:32
   9: hello_world_example::main::{{closure}}
             at ./examples/hello-world-example/src/main.rs:23:10
  10: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:63
  11: tokio::runtime::coop::with_budget
             at /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
  12: tokio::runtime::coop::budget
             at /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
  13: tokio::runtime::park::CachedParkThread::block_on
             at /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:31
  14: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/blocking.rs:66:9
  15: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  16: tokio::runtime::context::runtime::enter_runtime
             at /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
  17: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  18: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:363:45
  19: tokio::runtime::runtime::Runtime::block_on
             at /home/steve/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:335:13
  20: hello_world_example::main
             at ./examples/hello-world-example/src/main.rs:19:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by steveGuRen** [comment]
![image](https://github.com/user-attachments/assets/822f5a7a-17a8-4959-97cb-9344ec743d3e)
Is there any additional configuration needed? It looks like it hasn't been configured properly.

**Comment by holmofy** [comment]
You need to run it in the web-example directory.Because the path of the configuration file is relative to web-example

发自我的iPhone

**Comment by steveGuRen** [comment]
> You need to run it in the example directory.Because the path of the configuration file is relative to example

I don't know how run it too , something go wrong again.
![image](https://github.com/user-attachments/assets/69fa697d-c5e3-4b66-89c3-80d0c3596652)

**Comment by holmofy** [comment]
@steveGuRen run it in `hello-world-example` directory

**Comment by steveGuRen** [comment]
> @steveGuRen run it in `hello-world-example` directory. default config directory is `./config`. Or change [config_path](https://docs.rs/spring/latest/spring/app/struct.AppBuilder.html#method.config_file) to an absolute path.
I can't find `./config` directory. And I run it in `hello-world-example` directory , it still failed.
![image](https://github.com/user-attachments/assets/b1ea1493-7678-4b7d-a281-f4d994cc203c)

**Comment by holmofy** [comment]
[#94d5fd ](https://github.com/spring-rs/spring-rs/commit/94d5fd74dbf4449458b98165eb6e3af98dce94eb)

**Comment by steveGuRen** [comment]
> I forgot to add the configuration file for this project. [#94d5fd ](https://github.com/spring-rs/spring-rs/commit/94d5fd74dbf4449458b98165eb6e3af98dce94eb)
OK，I install pg with docker，so it can run. Thanks.
