### ISSUE TITLE
Where is the config load module?

### ISSUE THREAD

**Issue by steveGuRen** [spring-rs/spring-rs#50]
I find that the config dir can locate in the `spring rs` dir.And then I can debug it by click the debug button in vs code directly.It is more conviently.So I want to know the logic of loading configurations. And after learning the logic, I want to try to modify the load modules.
In java, loading modules in spring boot name `AutoConfig`.With `AutoConfig`, a lot of components can auto work when we just add them in pom.xml.Spring boot defines good examples for developers.
![image](https://github.com/user-attachments/assets/de33c094-7a7e-47fa-b945-5b2dbd231eb5)

**Comment by holmofy** [comment]
You can take a look at the code of [this module](https://github.com/spring-rs/spring-rs/tree/master/spring/src/config)
