### ISSUE TITLE
Add Fancy Starting Logs to Library Initialization

### ISSUE THREAD

**Issue by Phosphorus-M** [spring-rs/spring-rs#60]
I would like to propose enhancing the log messages that appear at the start of the library's execution to make them more informative and visually appealing.

As an example, here's the first output when running `cargo run` in a Rocket-RS project:

![image](https://github.com/user-attachments/assets/2f5b41c9-6864-4790-a4c5-bf5b76b29e39)
    
This type of formatted log gives clear and useful feedback to the user right from the start. It could include information like version number, configuration status, and any important warnings or reminders. This enhancement would improve user experience by providing a more engaging and informative initialization phase.

**Comment by holmofy** [comment]
I think part of your suggestion is acceptable. I will add some necessary debugging information, such as installed route. However, I think the log format of Rocket is not suitable for production environment for the following reasons:
1. The log needs to contain information such as log level and source file of the log, which will help analyze program problems through logs. Especially when logs are collected into centralized log analysis tools, such as ELK and OpenObserve, the structure of logs is very important.
2. Be wary of too many logs. Outputting logs will generate IO operations, which will affect the performance of runtime. Therefore, the goal of printing logs should be "few but enough" as much as possible.

**Comment by holmofy** [comment]
v0.2.8 release
