### ISSUE TITLE
spring_mail

### ISSUE THREAD

**Issue by isrun** [spring-rs/spring-rs#98]
get 返回发送成功，但是没有收到邮件。{
  "code": {
    "severity": "PositiveCompletion",
    "category": "MailSystem",
    "detail": "Zero"
  },
  "message": [
    "stub mailer send success"
  ]
}
配置
[mail]
host = "smtp.qq.com"                                    # SMTP邮件服务器地址，
port = 465                                              # SMTP服务器端口号
secure = true                                           # 响应超时时间，单位毫秒
stub = true
auth = { user = "kamft@qq.com", password = "ungltjbad" } # 认证信息

#[get("/mail/send")]
async fn send_mail(Component(mailer): Component<Mailer>) -> Result<impl IntoResponse> {
    let email = Message::builder()
        // 发送方
        .from("kamft <kamft@qq.com>".parse().unwrap())
        // 抄送
        .reply_to("QQmail <997995615@qq.com>".parse().unwrap())
        // 收件
        .to("997995615@qq.com".parse().unwrap())
        .subject("Happy new year")
        .header(ContentType::TEXT_PLAIN)
        .body(String::from("Be happy!"))
        .unwrap();
    let resp = mailer.send(email).await.context("发送邮件失败")?;
    Ok(Json(resp))
}

**Comment by isrun** [comment]
大佬。有微信群交流吗？

**Comment by holmofy** [comment]
不要用 stub 模式，这个模式主要用来测试的。用需要配置邮件服务器的正常模式

发自我的iPhone

**Comment by isrun** [comment]
![image](https://github.com/user-attachments/assets/5cb41672-4d16-4ac9-869b-b01356788116)
2024-11-20T15:58:42  INFO spring::app: spring_web::WebPlugin plugin registered
2024-11-20T15:58:42  INFO spring::app: spring_mail::MailPlugin plugin registered
2024-11-20T15:58:42  INFO spring::app: spring_redis::RedisPlugin plugin registered

**Comment by isrun** [comment]
参数配置也是照着文档上的。

**Comment by holmofy** [comment]
![image](https://github.com/user-attachments/assets/f9f2abcb-8d91-4aa1-a8f6-93e789339e45)
刚刚剪了个QQ群，后面用这个群交流

**Comment by holmofy** [comment]
`spring-mail = "0.2.2"` released
